//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsDocuments.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<decimal> Assistance { get; set; }
        public Nullable<int> IdTypeDocument { get; set; }
        public Nullable<int> IdStudent { get; set; }
        public Nullable<int> IdOrgEmpl { get; set; }
        public Nullable<int> IdOrgInst { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Organization Organization1 { get; set; }
        public virtual Status Status { get; set; }
        public virtual Student Student { get; set; }
        public virtual TypeDocument TypeDocument { get; set; }
    }
}
